name: start_up_workspace
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  http: ^1.1.2
  flutter_dotenv: ^5.1.0
  share_plus: ^7.2.1
  loading_plus: ^1.3.0
  cached_network_image: ^3.3.1 #chick if use
  transparent_image: ^2.0.1 #chick if use
  url_launcher: ^6.2.2 #chick if use
  awesome_notifications: ^0.8.3
  firebase_messaging: ^14.7.9
  package_info_plus: ^5.0.1
  country_picker: ^2.0.23 #chick if use
  flutter_svg: ^2.0.9 #chick if use
  internet_connection_checker: ^1.0.0+1
  image_cropper: ^5.0.1 #chick if use
  image_picker: ^1.0.5 #chick if use
  geolocator: ^10.1.0 #chick if use
  upgrader: ^8.4.0
  in_app_review: ^2.0.8
  shimmer: ^3.0.0 #chick if use
  encrypt: ^5.0.3

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  import_sorter: ^4.6.0
  ########## import_sorter ##########
import_sorter:
  emojis: false
  comments: false

# dart run import_sorter:main
########## import_sorter ##########

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  #  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

#  flutter pub get
#  dart run flutter_launcher_icons

########## flutter_launcher_icons ##########

########## flutter_native_splash ##########
flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/background.png"
  image: assets/icons/app_icon.png
  #branding: assets/dart.png
  # bottom, bottomRight, bottomLeft
  #branding_mode: bottom
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png
  android_12:
    color: "#ffffff"
    image: assets/icons/app_icon.png
  # dart run flutter_native_splash:create
  # dart run flutter_native_splash:remove
########## flutter_native_splash ##########

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    # - assets/gifs/
    # - assets/sounds/
    # - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 300